group_feed/group_feed/group/urls.py
from django.urls import path,re_path

from . import views

app_name = 'group'

urlpatterns = [
    path('',views.ListGroups.as_view(),name = "all"),
    path("new",views.CreateGroup.as_view(),name="create"),
    path('group/search',views.search_groups,name="search"),
    re_path(r"^posts/in/(?P<slug>[-\w]+)/$",views.SingleGroup.as_view(),name="single"),
    re_path(r"join/(?P<slug>[-\w]+)/$",views.JoinGroup.as_view(),name="join"),
    re_path(r"leave/(?P<slug>[-\w]+)/$",views.LeaveGroup.as_view(),name="leave"),
]

group_feed/group_feed/group_feed/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include("accounts.urls",namespace="accounts")),
    path('accounts/',include("django.contrib.auth.urls")),
    path('',views.HomePage.as_view(),name = "home"),
    path('tests/',views.TestPage.as_view(),name = "tests"),
    path('thanks/',views.ThanksPage.as_view(),name = "thanks"),
    path('posts/',include("post.urls",namespace="post")),
    path('groups/',include("group.urls",namespace="group")),
]

group_feed/group_feed/post/urls.py
from django.urls import path

from . import views

app_name='post'

urlpatterns = [
    path("", views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<str:username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<str:username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
    path('post/<int:pk>/comment/',views.add_comment_to_post,name='add_comment'),
    path('comment/<int:pk>/remove/',views.remove_comment,name='remove_comment'),
]

group_feed/group_feed/group/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.utils.text import slugify
from django.contrib.auth import get_user_model
# Create your models here.
import misaka

User = get_user_model()

from django import template
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length = 255,unique = True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False,default='',blank=True)
    members = models.ManyToManyField(User,through="GroupMember")

    def __str__(self):
         return self.name
    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args,**kwargs)
    def get_absolute_url(self):
        return reverse("group:single",kwargs={"slug":self.slug})

    class Meta:
        ordering=["name"]
class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name="memberships",on_delete = models.CASCADE)
    user = models.ForeignKey(User,related_name='user_groups',on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ("group","user")

group_feed/group_feed/group/views.py
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin)
from django.urls import reverse
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views import generic
from group.models import Group,GroupMember
from . import models
# Create your views here.
class CreateGroup(LoginRequiredMixin,generic.CreateView):
    fields = ("name","description")
    model = Group
class SingleGroup(generic.DetailView):
    model = Group
class ListGroups(generic.ListView):
    model = Group

class JoinGroup(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        return reverse("group:single",kwargs={"slug":self.kwargs.get("slug")})
    def get(self,request,*args,**kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get("slug"))

        try:
            GroupMember.objects.create(user = self.request.user,group = group)
        except IntegrityError:
            messages.warning(self.request,(" WARNING: Already a member of the group {}".format(group.name)))
        else:
            messages.success(self.request,(" You are now a member of the group {}".format(group.name)))
        return super().get(request,*args,**kwargs)
class LeaveGroup(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        return reverse("group:single",kwargs={"slug":self.kwargs.get("slug")})
    def get(self,request,*args,**kwargs):
        try:
            membership = models.GroupMember.objects.filter(
            user=self.request.user,
            group__slug=self.kwargs.get("slug")).get()
        except models.GroupMember.DoesNotExist:
            messages.warning(self.request,"You can't leave this group because you are not a member of this group")
        else:
            membership.delete()
            messages.success(self.request,"You have successfully left this group")
        return super().get(request,*args,**kwargs)
def search_groups(request):
    if request.method == "POST":
        searched = request.POST['searched']
        groups = models.Group.objects.filter(name__icontains=searched)
        # Use render() method to generate HTML page by combining
        # template and context
        return render(request,"group/search_group.html",{'searched':searched,'searched_groups':groups})
    else:
        searched = None
        learning_guides = LearningGuide.objects.all()
        indicators = Indicator.objects.all()
        return render(request,"learning_guides_app/search_learning_guides.html",{'searched':searched,'searched_learning_guides':learning_guides,'indicators':indicators,'homepage':False})

group_feed/group_feed/group/templates/group/group_base.html
{% extends "base.html"%}
{% block content %}
<div class="container">
  <div class="row">
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block postgroup %}{% endblock %}
  </div>
</div>
{% endblock %}

group_feed/group_feed/group/templates/group/group_detail.html
{% extends "group/group_base.html" %}
{% block pregroup %}
<div class="head-section" style="text-align:center;padding:4em;">
  <h1 class = "group-name" >{{group.name}}</h1>
  {% if user in group.members.all %}
    <a href="{% url 'group:leave' slug=group.slug%}" class = "btn btn-lg btn-warning group-button">Leave</a>
  {% else %}
    <a href="{% url 'group:join' slug=group.slug%}" class = "btn btn-lg btn-success group-button">Join</a>
  {% endif %}
</div>
<div class="col-xs-4 sidebar">
  <h3 class="sidebar-top">About community</h3>
  <p class = "group-description">{{group.description}}</p>
  <p class = "group-member-count">Member: {{group.members.count}}  Post: {{group.posts.count}}</p>
  {% if user in group.members.all %}
  <a href="{% url 'post:create' %}" class = "btn btn-success">Create a post</a>
  {% endif %}
</div>
{% endblock %}
{% block group_content %}

  <div class="col-xs-8">
    {% if group.posts.count == 0 %}
    <div class="" style="background-color:white;padding:2em;border-radius:0.5em;">
      <h2>No posts  in this group </h2>
    </div>
    {% else %}
      {% for post in group.posts.all %}
        {% include "post/_individual_post.html" with hide_group=True%}
      {% endfor %}
    {% endif %}
  </div>


{% endblock %}

group_feed/group_feed/group/templates/group/group_form.html
{% extends "group/group_base.html" %}
{% load bootstrap5 %}
{% block group_content %}
<h4 style="margin-top:20px;color: white;text-align: center;">Create a New Group</h4>
  <form id="groupForm" action="{% url 'group:create'%}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Create" class = "btn btn-primary">
  </form>
{% endblock %}

group_feed/group_feed/group/templates/group/group_list.html
{% extends "group/group_base.html"%}
{% block pregroup %}
<div class="head-section" style = "background-color:#24968dd6;border-bottom:2px solid grey;">
  <h2 style = "text-align:center;font-size:xx-large;font-weight:bolder;margin-bottom:1em;margin-top:1em;">Your Groups</h2>
  {% if user.is_authenticated %}
    <a href="{% url 'group:create' %}" class = "btn btn-warning">Create New Group</a>
  {% endif %}
</div>
{% endblock %}

{% block group_content %}
  <div class="col-mid-8">
    <!-- one card -->
    <div class="list-group">
      {% for group in object_list %}
      {% if user in group.members.all %}
      <div class="card w-100" style="margin-bottom:1em;padding:1.5em; box-shadow:0em .5em 1em">
        <div class="row">
          <div class="card-body">
            <h3 class = "card-title">{{ group.name }}</h3>
            <p class= "card-text">{{ group.description_html|safe|truncatewords_html:15 }}</p>
            <p>Member: {{group.members.count}}  Post: {{group.posts.count}}</p>
            <a href="{% url 'group:single' slug=group.slug %}" class = "btn btn-primary" style = "float:left;padding-right:2em;padding-left:2em;padding-top:1em;padding-bottom:1em;text-align:center;"> Go to Group</a>
          </div>
        </div>
      </div>
      {% endif %}
      {% endfor %}
    </div>
  </div>

{% endblock %}

group_feed/group_feed/group/templates/group/search_group.html
{% extends "group/group_base.html"%}
  {%block pregroup%}
  <div class="container" style = "margin: 2em;padding: 2em;">
    {% if searched %}
    <h3 style="color:white;">"{{searched_groups.count}}" results found for {{searched}}</h3>
    {% endif %}
    <hr>
  {% endblock %}
  {% block group_content %}
    <div class="col-mid-8">
      <!-- one card -->
      <div class="list-group">
        {% for group in searched_groups %}

        <div class="card w-100" style="margin-bottom:1em;padding:1.5em; box-shadow:0em .5em 1em">
          <div class="row">
            <div class="card-body">
              <h3 class = "card-title">{{ group.name }}</h3>
              <p class= "card-text">{{ group.description_html|safe|truncatewords_html:15 }}</p>
              <p>Member: {{group.members.count}}  Post: {{group.posts.count}}</p>
              <a href="{% url 'group:single' slug=group.slug %}" class = "btn btn-primary" style = "float:left;padding-right:2em;padding-left:2em;padding-top:1em;padding-bottom:1em;text-align:center;"> Go to Group</a>
            </div>
          </div>
        </div>

        {% endfor %}
      </div>
    </div>

  {% endblock %}