group_feed/group_feed/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name = "accounts/login.html"),name = 'login'),
    path('logout/',auth_views.LogoutView.as_view(),name = "logout"),
    path('signup/',views.SignUp.as_view(),name = "signup"),
]

group_feed/group_feed/group/urls.py
from django.urls import path,re_path

from . import views

app_name = 'group'

urlpatterns = [
    path('',views.ListGroups.as_view(),name = "all"),
    path("new",views.CreateGroup.as_view(),name="create"),
    path('group/search',views.search_groups,name="search"),
    re_path(r"^posts/in/(?P<slug>[-\w]+)/$",views.SingleGroup.as_view(),name="single"),
    re_path(r"join/(?P<slug>[-\w]+)/$",views.JoinGroup.as_view(),name="join"),
    re_path(r"leave/(?P<slug>[-\w]+)/$",views.LeaveGroup.as_view(),name="leave"),
]

group_feed/group_feed/group_feed/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include("accounts.urls",namespace="accounts")),
    path('accounts/',include("django.contrib.auth.urls")),
    path('',views.HomePage.as_view(),name = "home"),
    path('tests/',views.TestPage.as_view(),name = "tests"),
    path('thanks/',views.ThanksPage.as_view(),name = "thanks"),
    path('posts/',include("post.urls",namespace="post")),
    path('groups/',include("group.urls",namespace="group")),
]

group_feed/group_feed/post/urls.py
from django.urls import path

from . import views

app_name='post'

urlpatterns = [
    path("", views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<str:username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<str:username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
    path('post/<int:pk>/comment/',views.add_comment_to_post,name='add_comment'),
    path('comment/<int:pk>/remove/',views.remove_comment,name='remove_comment'),
]

group_feed/group_feed/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Group Feed</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/group_feed/css/top_navigation_bar.css' %}">
    <link rel="stylesheet" href="{% static 'post/css/individual_post.css' %}">
    <link rel="stylesheet" href="{% static 'css/group/group_detail.css' %}">

  </head>
  <body style="background-color:grey;">
    <nav class="navbar navbar-expand-md navbar-light" role="navigation" id="navbar" style="background-color:white;">
    			<div class="container">

            <a class="navbar-brand top_nav_item" href="{% url 'home' %}">Social Feed</a>
            <button class = "navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target = "#top_navbar" aria-controls="top_navbar" aria-expanded = "false" aria-label = "Top navigation bar">
                  <span class="navbar-toggler-icon"></span>
            </button>
            <div class=" collapse navbar-collapse" id = "top_navbar">
    					<ul class="navbar-nav ms-auto">
                <li class = "nav-item">
                  <form class="form-inline input-group my-2 my-lg-0" action="{% url 'group:search' %}" method="POST">
                    {% csrf_token %}
                    <input id = "input_search" class="form-control me-sm-2" type="search" placeholder="Search" aria-label="Search" name = "searched">
                    <button id = "button-addon2" class = "btn btn-outline-success btn-info my-2 my-sm-0" type="submit">Search</button>
                  </form>
                </li>
    						{% if user.is_authenticated %}
                    <li class="nav-item"><a href="{% url 'post:for_user' username=user.username%}" class="btn btn-simple top_nav_item" >Post</a></li>
                    <li class="nav-item"><a href="{% url 'post:create' %}" class="btn btn-simple top_nav_item">Create Post</a></li>
                    <li class="nav-item"><a href="{% url 'group:all' %}" class="btn btn-simple top_nav_item">Groups</a></li>
                    <li class="nav-item"><a href="{% url 'group:create' %}" class="btn btn-simple top_nav_item">Create Group</a></li>
                    <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="btn btn-simple top_nav_item">Log out</a></li>
    						{% else %}
    						     <li class="nav-item"><a href="{% url 'group:all' %}"class="btn btn-simple top_nav_item">Groups</a></li>
    						     <li class="nav-item"><a href="{% url 'accounts:login' %}" class="btn btn-simple top_nav_item">Log in</a></li>
    						     <li class="nav-item"><a href="{% url 'accounts:signup' %}" class="btn btn-simple top_nav_item">Sign up</a></li>
    						{% endif %}
    					</ul>
            </div>
    			</div>
    		</nav>
        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>

  </body>
</html>

group_feed/group_feed/templates/index.html
{% extends "base.html" %}
{% block content %}
    <div class="homepage-contents">
      <div class="row">
        <div class="col-xs-6"style="min-width: 70%;max-width: 70%;">
          <div class="" style = "padding:5em; background-color:#4491a0;margin-top:5em;margin-right:2em;border-radius:0.5em;">
          <div class=" post-text" style="color:white;">
            {% if posts_list.count == 0 %}
            <h1>no posts</h1>
            {% else %}
            <h1 style="text-align:center;">Posts</h1>
            {% endif %}
          </div>
          <hr style= "margin-bottom: 2em;">
          {% for post in posts_list %}
            <div class="row">
              <div class="card" style="margin-bottom:1em;padding:1.5em; box-shadow:0em .5em 1em;width:100%">
                <div class="row">
                  <div class="card-body">
                    <h3 class = "card-title">{{ post.title }}</h3>
                    <p class= "card-text">{{ post.message_html|safe|truncatewords_html:15 }}</p>
                    <p>Created by: <a href="{% url 'post:for_user' username=post.user.username%}"style="text-decoration:none;"> {{post.user.username}}</a>
                       Date: <time> {{post.created_at}} </time></p>
                    {% if post.group and not hide_group %}
                      <p>Group :<a href="{% url 'group:single' slug=post.group.slug%}"style="text-decoration:none;">{{ post.group.name }}</a></p>
                    {% endif %}

                    <div class="media-footer">
                      <a href="{% url 'post:single' username=post.user.username pk=post.pk %}" class = "btn btn-primary" style = "float:left;padding-right:2em;padding-left:2em;padding-top:1em;padding-bottom:1em;text-align:center;"> Go to Post</a>
                      {% if user.is_authenticated and post.user == user and not hide_delete%}
                      <a href="{% url 'post:delete' pk=post.pk %}" class = "btn btn-danger" style = "float:right;padding-right:2em;padding-left:2em;padding-top:1em;padding-bottom:1em;text-align:center;"> Delete</a>
                      {% endif %}

                    </div>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
          </div>
        </div>
        <div class="col-xs-4"style="min-width: 30%;max-width: 30%;">
          <div class="" style="padding:2em; background-color:#4491a0;margin-top:5em;border-radius:0.5em;">
            <div class="head-group-text" style="text-align:center;margin-top:4em; color:white;">
              <h3>Your Groups</h3>
            </div>
            <hr style= "margin-bottom: 2em;">
            {% for group in user_groups %}
            <div class="row">
              <div class="card" style="margin-bottom:1em;padding:1.5em; box-shadow:0em .5em 1em;width:100%">
                <div class="row">
                  <div class="card-body">
                    <h3 class = "card-title">{{ group.name }}</h3>
                    <p class= "card-text">{{ group.description_html|safe|truncatewords_html:15 }}</p>
                    <p>Member: {{group.members.count}}  Post: {{group.posts.count}}</p>
                    <a href="{% url 'group:single' slug=group.slug %}" class = "btn btn-primary" style = "float:left;padding-right:2em;padding-left:2em;padding-top:1em;padding-bottom:1em;text-align:center;"> Go to Group</a>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>

    </div>
{% endblock %}

group_feed/group_feed/templates/tests.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>You are now logged in!</h1>
  <h2><a href="{% url 'group:all'%}">Go to Groups</a></h2>


</div>




{% endblock %}

group_feed/group_feed/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<div class=""style="text-align:center;background-color:white;margin:5em;padding:2em;border-radius:0.5em;">
  <h1>Thanks for visiting! Come back soon!</h1>
</div>

{% endblock %}