group_feed/group_feed/group_feed/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include("accounts.urls",namespace="accounts")),
    path('accounts/',include("django.contrib.auth.urls")),
    path('',views.HomePage.as_view(),name = "home"),
    path('tests/',views.TestPage.as_view(),name = "tests"),
    path('thanks/',views.ThanksPage.as_view(),name = "thanks"),
    path('posts/',include("post.urls",namespace="post")),
    path('groups/',include("group.urls",namespace="group")),
]

group_feed/group_feed/post/urls.py
from django.urls import path

from . import views

app_name='post'

urlpatterns = [
    path("", views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<str:username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<str:username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
    path('post/<int:pk>/comment/',views.add_comment_to_post,name='add_comment'),
    path('comment/<int:pk>/remove/',views.remove_comment,name='remove_comment'),
]

group_feed/group_feed/post/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
import misaka
from group.models import Group
from django.contrib.auth import get_user_model
User = get_user_model()
# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User,related_name = "posts",on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable = False)
    group = models.ForeignKey(Group,related_name="posts",null=True,blank = True,on_delete=models.CASCADE)
    title = models.TextField(max_length=256,default="Title")
    def __str__(self):
        return self.message
    def save(self,*args,**kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse("post:single",kwargs={"username":self.user.username,"pk":self.pk})

    class Meta:
        ordering = ["-created_at"]
        unique_together=["user","message"]
class Comment(models.Model):
    post = models.ForeignKey(Post,related_name="comments",on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now=True)
    user=models.ForeignKey(User,related_name="comments",on_delete=models.CASCADE)
    def __str__(self):
        return self.text
    def save(self,*args,**kwargs):
        self.text_html = misaka.html(self.text)
        super().save(*args,**kwargs)
    class Meta:
        ordering = ["-created_at"]
        unique_together=["user","text"]

group_feed/group_feed/post/forms.py
from django import forms
from post import models

class PostForm(forms.ModelForm):
    class Meta:
        fields = ("title","message","group")
        model = models.Post
    def __init__(self,*args,**kwargs):
        user = kwargs.pop("user",None)
        super().__init__(*args,*kwargs)
        if user is not None:
            self.fields["group"].queryset = (
                models.Group.objects.filter(
                pk__in=user.group.values_list("group__pk")
                )
            )
        # TODO : filter groups 
class CommentForm(forms.ModelForm):
    class Meta():
        model = models.Comment
        fields = ('text',)

group_feed/group_feed/post/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
## know about this
from braces.views import SelectRelatedMixin
from django.urls import reverse_lazy
from django.http import Http404
from django.views import generic
from django.contrib.auth.decorators import login_required

from . import models,forms
from django.contrib.auth import get_user_model
# Create your views here.
User = get_user_model()

class PostList(SelectRelatedMixin,generic.ListView):
    # the list of post related to the user and the group
    model = models.Post
    select_related = ("user","group")

class UserPosts(generic.ListView):
    # all the post of the user
    model = models.Post
    template_name = "post/user_post_list.html"

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
            username__iexact=self.kwargs.get("username")
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context["post_user"]=self.post_user
        return context

class PostDetail(SelectRelatedMixin,generic.DetailView):
    # the details of a post
    model = models.Post
    select_related = ("user","group")

    def get_queryset(self):
        # know about this
        queryset = super().get_queryset()
        return queryset.filter(
        user__username__iexact=self.kwargs.get("username")
        )
class CreatePost(LoginRequiredMixin,SelectRelatedMixin,generic.CreateView):
    fields = ('message','group')
    model = models.Post

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)
class DeletePost(LoginRequiredMixin,SelectRelatedMixin,generic.DeleteView):
    model = models.Post
    select_related = ("user","group")
    success_url = reverse_lazy("home")

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self,*args,**kwargs):
        messages.success(self.request,"Post Deleted")
        return super().delete(*args,**kwargs)

@login_required
def add_comment_to_post(request,pk):
    post = get_object_or_404(models.Post,pk = pk)
    if request.method == 'POST':
        form = forms.CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit = False)
            comment.post = post
            comment.user = request.user
            comment.save()
            return redirect('post:single',username=post.user.username,pk = post.pk)
    else:
        form = forms.CommentForm()
    return render(request,'post/comment_form.html',{'form':form})
@login_required
def remove_comment(request,pk):
    comment = get_object_or_404(models.Comment,pk = pk)
    post_pk = comment.post.pk
    post_name = comment.post.user.username
    comment.delete()
    return redirect('post:single',username=post_name,pk = post_pk)

group_feed/group_feed/post/templates/post/_individual_post.html
<!-- each individual post-->

<div class="card" style="margin-bottom:1em;padding:1.5em; box-shadow:0em .5em 1em;width:100%">
  <div class="row">
    <div class="card-body">
      <h3 class = "card-title">{{ post.title }}</h3>
      <p class= "card-text">{{ post.message_html|safe|truncatewords_html:15 }}</p>
      <p>Created by: <a href="{% url 'post:for_user' username=post.user.username%}" style="text-decoration:none;"> {{post.user.username}}</a>
         Date: <time> {{post.created_at}} </time></p>
      {% if post.group and not hide_group %}
        <p>Group :<a href="{% url 'group:single' slug=post.group.slug%}"style="text-decoration:none;">{{ post.group.name }}</a></p>
      {% endif %}

      <div class="media-footer">
        <a href="{% url 'post:single' username=post.user.username pk=post.pk %}" class = "btn btn-primary" style = "float:left;padding-right:2em;padding-left:2em;padding-top:1em;padding-bottom:1em;text-align:center;"> Go to Post</a>
        {% if user.is_authenticated and post.user == user and not hide_delete%}
        <a href="{% url 'post:delete' pk=post.pk %}" class = "btn btn-danger" style = "float:right;padding-right:2em;padding-left:2em;padding-top:1em;padding-bottom:1em;text-align:center;"> Delete</a>
        {% endif %}

      </div>
    </div>
  </div>
</div>

group_feed/group_feed/post/templates/post/_post.html
<!-- details of a post-->
<div class="container" style = "padding:1em;margin-top:1em;margin-left:1em;margin-right:1em;margin-bottom:.5em;">
  <h1 class = "post-title" style="font-size:xxx-large;font-weight:bolder;">{{post.title}}</h1>

  <p style = "font-size:medium">Created by: <a href="{% url 'post:for_user' username=post.user.username%}"style="text-decoration:none;"> {{post.user.username}}</a>
     Date: <time> {{post.created_at}} </time>
     {% if post.group and not hide_group %}
     Group : <a href="{% url 'group:single' slug=post.group.slug%}"style="text-decoration:none;">{{ post.group.name }}</a>
     {% endif %}
  </p>
  <p class = "post-text" style = "font-size:xx-large;padding:1em;border:1px solid grey;border-radius:25px;margin-right:2em;" >{{ post.message}}</p>
  {% if not hide_delete %}
    <div class="buttons" style = "display:block">


      {% if post.user == request.user%}
        <a href="{% url 'home' %}" class = "btn btn-success" style = "float:left;padding-right:2em;padding-left:2em;padding-top:1em;padding-bottom:1em;text-align:center;margin-right:5px;margin-left:2%;"> Done</a>

        <!-- TODO:change to create comment url -->
        <a href="{% url 'post:add_comment' pk=post.pk %}" class = "btn btn-success" style = "float:left;padding-right:2em;padding-left:2em;padding-top:1em;padding-bottom:1em;text-align:center;margin-left:25%;"> Comment</a>

        <a href="{% url 'post:delete' pk=post.pk %}" class = "btn btn-danger" style = "float:right;padding-right:2em;padding-left:2em;padding-top:1em;padding-bottom:1em;text-align:center;margin-right:10%"> Delete</a>
      {% else %}
        <a href="{% url 'post:add_comment' pk=post.pk %}" class = "btn btn-success" style = "float:left;padding-right:2em;padding-left:2em;padding-top:1em;padding-bottom:1em;text-align:center;margin-left:5px;"> Comment</a>
      {%endif%}
    </div>
  {% endif %}

</div>

group_feed/group_feed/post/templates/post/comment_form.html
<!-- TODO: fix comment UI and search bar-->
{% extends "post/post_base.html" %}
{% load bootstrap5 %}

{% block post_content %}
<h4 style = "margin-top:20px;color: white;text-align: center;">Create New comment</h4>
<form  method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" value="Post Comment" class = "btn btn-primary btn-large">
</form>
{% endblock %}

group_feed/group_feed/post/templates/post/post_base.html
{% extends "base.html" %}

{% block content %}
<div class="posts-page">
  <div class="container">
    <div class="row">
      {% block prepost%}{% endblock %}
			{% block post_content %}{% endblock %}
			{% block post_post%}{% endblock %}
    </div>
  </div>
</div>
{% endblock %}

group_feed/group_feed/post/templates/post/post_confirm_delete.html
{% extends "post/post_base.html" %}
{% block post_content %}
<div class="delete-post-container" style = "background-color:white; padding:1em;margin-top:2em;border-radius:15px;">
<h3 style = "margin-left:20px;margin-top:20px;">Are you sure you want to delete this post?</h3>
  <div class="posts">
    {% include "post/_post.html" with post=object hide_delete=True %}
    <form method="post">
      {% csrf_token %}
        <input type="submit" value="Confirm Delete" class = "btn btn-danger btn-large" style="padding-left:1.5em;margin-left:3em;">
        <a href="{% url 'post:single' username=user.username pk=object.pk %}" class = "btn btn-primary btn-large btn-default">Cancel</a>
    </form>
  </div>
</div>
{% endblock %}

group_feed/group_feed/post/templates/post/post_detail.html
{% extends "post/post_base.html" %}
{% block post_content%}
<div class="col-mid-8" style = "background-color:white;margin-top:1em;border:1px white solid;border-radius:15px;">
  <div class="post_detail_entire" style = "margin-bottom:10px;">
  {% include "post/_post.html" %}

  <!-- TODO: the ability to edit post and fix the comment form UI, edit,group,homepage-->
  </div>
  <hr style = "clear:both;margin-top:5%">
  <h3 style = "margin-left:2em;margin-top:1em;">Comments:</h3>
  <div class="container" style = "margin:2em;">
    {% if post.comments.all %}
      {% for comment in post.comments.all %}
        <div class="comment" style ="border:solid grey 1px;border-radius:1em; padding:1.5%;margin-bottom:10px;margin-right:5em;">
        <p><strong>{{comment.user.username}}</strong></p>
        <p style="font-size:large">{{comment.text|safe|linebreaksbr}}</p>
        <p style="font-size:small">Date:<time>{{comment.created_at}}</time></p>
        </div>
        {% if comment.user == request.user%}
          <a class="btn btn-danger" href="{% url 'post:remove_comment' pk=comment.pk %}" style="margin-bottom:1em;margin-left:1%;">Remove</a>
        {%endif%}
      {%endfor%}
    {% else %}
      <p>No comments posted </p>
    {% endif %}

  </div>
</div>
{% endblock %}

group_feed/group_feed/post/templates/post/post_form.html
{% extends "post/post_base.html" %}
{% load bootstrap5 %}

{% block post_content %}
<h4 style = "margin-top:20px;color: white;text-align: center;">Create New Post</h4>
<form id="postForm" action="{% url 'post:create' %}" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" value="Post" class = "btn btn-primary btn-large">
</form>
{% endblock %}

group_feed/group_feed/post/templates/post/post_list.html
{% extends "post/post_base.html" %}
{% block prepost %}

  <p style="text-align:left; font-weight:bolder; margin-top:1em;margin-bottom:1em; color:white;font-size:x-large">ALL POSTS</p>
  <hr>
{% endblock %}

{% block post_content %}
<div class="container" style = "margin-top:1em;">

  {% for post in post_list %}
    {% include "post/_individual_post.html" %}
  {% endfor %}
</div>

{%endblock%}

group_feed/group_feed/post/templates/post/user_post_list.html
{% extends "post/post_base.html" %}
{% block prepost %}

  <p style="text-align:left; font-weight:bolder; margin-top:1em;margin-bottom:1em; color:white;font-size:x-large">All the posts by {{post_user.username|upper}}</p>
  <hr>
{% endblock %}

{% block post_content %}
<div class="container" style = "margin-top:1em;">

  {% for post in post_list %}
    {% include "post/_individual_post.html" %}
  {% endfor %}
</div>

{%endblock%}